### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by calren** [cherylfong/R33l#1]
Haha, yeah the lab is definitely a lot of fun to work on as well! Looking forward to seeing your Flicks app

**Comment by calren** [comment]
Glad to see you were able to get week 1 requirements down! Let us know if you need any help with the week 2 features. (Should be considerably easier than week 1!)

**Comment by cherylfong** [comment]
Hi @calren thanks for dropping a note and offering help :smile: , see R33l's [README](https://github.com/cherylfong/R33l/blob/master/README.md) for week 1 and week 2 updates. Thank you !
